package:
  name: mrfbp
  version: '1.2'

source:
  git_url: https://github.com/dmpelt/pymrfbp.git
  git_tag: 1.2

build:
  number: 0

test:
  imports:
    - mrfbp

requirements:
  build:
    - python

  run:
    - python
    - astra-toolbox
    - scipy
    - six
    - numpy

about:
  home: http://dmpelt.github.io/pymrfbp/
  license: GPLv3
  summary: 'Python implementation of the MR-FBP tomographic reconstruction method, published in Pelt, D. M., & Batenburg, K. J. (2014). Improving Filtered Backprojection Reconstruction by Data-Dependent Filtering. Image Processing, IEEE Transactions on, 23(11), pp. 4750-4762.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
